version: '3.8'
services:
  server_web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - server-postgres
  server_postgres:
    image: postgres:18
    environment:
      POSTGRES_USER: KyleAngeles            # Matches your user folders
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: kyle_angeles_db
    volumes:
     - "../backend/database/:docker-entrypoint-initdb.d"